"""add_notification_routing

Revision ID: 05a702abdbd0
Revises: 1f4e9384a23a
Create Date: 2026-01-29 13:53:50.858198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a702abdbd0'
down_revision: Union[str, None] = '1f4e9384a23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_frequency', sa.String(), nullable=True),
    sa.Column('force_critical', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('notifications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'batch_id')
    op.drop_column('notifications', 'event_type')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'status')
    op.drop_table('user_notification_preferences')
    # ### end Alembic commands ###
