"""add_ticket_assets_link

Revision ID: 06bd8024a026
Revises: 1c8034c0600b
Create Date: 2026-01-20 13:11:06.950177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bd8024a026'
down_revision: Union[str, None] = '1c8034c0600b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_assets',
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_contacts', 'contact_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ticket_contacts', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('ticket_assets')
    # ### end Alembic commands ###
