"""add_article_history

Revision ID: 0c6fecaf2aee
Revises: 06bd8024a026
Create Date: 2026-01-20 18:12:59.228031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6fecaf2aee'
down_revision: Union[str, None] = '06bd8024a026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('snapshot_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_contacts', 'contact_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ticket_contacts', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('article_history')
    # ### end Alembic commands ###
