"""add_totp_secret

Revision ID: 0ca6f2240b5a
Revises: a6df3e39ce34
Create Date: 2026-01-23 00:17:28.694460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca6f2240b5a'
down_revision: Union[str, None] = 'a6df3e39ce34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
