"""add_category_to_audit_templates

Revision ID: 1bad485d2571
Revises: 452215b5d598
Create Date: 2026-02-07 21:35:47.164734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bad485d2571'
down_revision: Union[str, None] = '452215b5d598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_templates', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_templates', 'category')
    # ### end Alembic commands ###
