"""add_recurring_revenue_fields

Revision ID: 1f4e9384a23a
Revises: 4d593b3c7108
Create Date: 2026-01-27 13:58:11.829087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4e9384a23a'
down_revision: Union[str, None] = '4d593b3c7108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('expires_at', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('linked_product_id', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('auto_invoice', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'assets', 'products', ['linked_product_id'], ['id'])
    op.add_column('products', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('billing_frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'billing_frequency')
    op.drop_column('products', 'is_recurring')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'auto_invoice')
    op.drop_column('assets', 'linked_product_id')
    op.drop_column('assets', 'vendor')
    op.drop_column('assets', 'expires_at')
    # ### end Alembic commands ###
