"""Add financial locking and payment tracking

Revision ID: 2a075b31d9be
Revises: 4580c0c0625f
Create Date: 2026-02-15 21:03:02.122218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a075b31d9be'
down_revision: Union[str, None] = '4580c0c0625f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('ticket_materials', sa.Column('invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ticket_materials', 'invoices', ['invoice_id'], ['id'])
    op.add_column('ticket_time_entries', sa.Column('invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'ticket_time_entries', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_time_entries', type_='foreignkey')
    op.drop_column('ticket_time_entries', 'invoice_id')
    op.drop_constraint(None, 'ticket_materials', type_='foreignkey')
    op.drop_column('ticket_materials', 'invoice_id')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'paid_at')
    # ### end Alembic commands ###
