"""add_pg_trgm_fuzzy_search

Revision ID: 32bf70f79f6c
Revises: 84474191672f
Create Date: 2026-03-05 21:06:36.431149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bf70f79f6c'
down_revision: Union[str, None] = '84474191672f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trgm_account_name', 'accounts', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_trgm_article_content', 'articles', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index('ix_trgm_article_title', 'articles', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_trgm_asset_name', 'assets', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_trgm_contact_first_name', 'contacts', ['first_name'], unique=False, postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops'})
    op.create_index('ix_trgm_contact_last_name', 'contacts', ['last_name'], unique=False, postgresql_using='gin', postgresql_ops={'last_name': 'gin_trgm_ops'})
    op.create_index('ix_trgm_milestone_name', 'milestones', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_trgm_product_description', 'products', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_trgm_product_name', 'products', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_trgm_project_name', 'projects', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_trgm_ticket_description', 'tickets', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_trgm_ticket_resolution', 'tickets', ['resolution'], unique=False, postgresql_using='gin', postgresql_ops={'resolution': 'gin_trgm_ops'})
    op.create_index('ix_trgm_ticket_subject', 'tickets', ['subject'], unique=False, postgresql_using='gin', postgresql_ops={'subject': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trgm_ticket_subject', table_name='tickets', postgresql_using='gin', postgresql_ops={'subject': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_ticket_resolution', table_name='tickets', postgresql_using='gin', postgresql_ops={'resolution': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_ticket_description', table_name='tickets', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_project_name', table_name='projects', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_product_name', table_name='products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_product_description', table_name='products', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_milestone_name', table_name='milestones', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_contact_last_name', table_name='contacts', postgresql_using='gin', postgresql_ops={'last_name': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_contact_first_name', table_name='contacts', postgresql_using='gin', postgresql_ops={'first_name': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_asset_name', table_name='assets', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_article_title', table_name='articles', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_article_content', table_name='articles', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_index('ix_trgm_account_name', table_name='accounts', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
