"""add_vendor_risk_fields

Revision ID: 32c61e966a2d
Revises: de4e5a387b79
Create Date: 2026-02-13 14:23:56.249700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c61e966a2d'
down_revision: Union[str, None] = 'de4e5a387b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('is_critical', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'is_critical')
    op.drop_column('vendors', 'risk_score')
    # ### end Alembic commands ###
