"""add_vendor_risk_metrics

Revision ID: 4580c0c0625f
Revises: 5b5793da23f4
Create Date: 2026-02-13 20:38:22.389958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4580c0c0625f'
down_revision: Union[str, None] = '5b5793da23f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('compliance_status', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('last_audit_date', sa.DateTime(), nullable=True))
    op.add_column('vendors', sa.Column('data_access_level', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('security_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'security_score')
    op.drop_column('vendors', 'data_access_level')
    op.drop_column('vendors', 'last_audit_date')
    op.drop_column('vendors', 'compliance_status')
    op.drop_column('vendors', 'risk_level')
    # ### end Alembic commands ###
