"""add_cascade_delete_users

Revision ID: 4d593b3c7108
Revises: 72fd92a5879b
Create Date: 2026-01-24 08:27:04.081110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d593b3c7108'
down_revision: Union[str, None] = '72fd92a5879b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('password_tokens_user_id_fkey', 'password_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_tokens', type_='foreignkey')
    op.create_foreign_key('password_tokens_user_id_fkey', 'password_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
