"""add_account_ingest_token

Revision ID: 5b5793da23f4
Revises: e9353469f96d
Create Date: 2026-02-13 16:40:01.915943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5793da23f4'
down_revision: Union[str, None] = 'e9353469f96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('ingest_token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True))
    op.create_unique_constraint(None, 'accounts', ['ingest_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'ingest_token')
    # ### end Alembic commands ###
