"""add change_comment to article_history

Revision ID: 81566a52c5f9
Revises: f034e386f7ad
Create Date: 2026-03-09 10:33:54.584020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81566a52c5f9'
down_revision: Union[str, None] = 'f034e386f7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('change_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_history', 'change_comment')
    # ### end Alembic commands ###
