"""add_ticket_relations

Revision ID: 84474191672f
Revises: fc78ff647823
Create Date: 2026-03-04 15:26:08.139160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84474191672f'
down_revision: Union[str, None] = 'fc78ff647823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_relations',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('relates_to', 'blocks', 'duplicates', name='ticket_relation_type'), nullable=False),
    sa.Column('visibility', sa.Enum('internal', 'public', name='ticket_relation_visibility'), nullable=False),
    sa.ForeignKeyConstraint(['related_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'related_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_relations')
    # ### end Alembic commands ###
