"""baseline_schema_v1_7

Revision ID: 85a9a4b51bdf
Revises: 
Create Date: 2026-01-14 17:17:38.807676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85a9a4b51bdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('accounts', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('accounts_assigned_manager_id_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'created_at')
    op.drop_column('accounts', 'assigned_manager_id')
    op.drop_column('audit_reports', 'generated_at')
    op.drop_constraint('campaign_targets_unique', 'campaign_targets', type_='unique')
    op.drop_constraint('campaign_targets_campaign_id_fkey', 'campaign_targets', type_='foreignkey')
    op.drop_constraint('campaign_targets_contact_id_fkey', 'campaign_targets', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_targets', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'campaign_targets', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('campaigns', 'budget_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('comments', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('comments_ticket_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_deal_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_audit_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'audit_reports', ['audit_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'deals', ['deal_id'], ['id'])
    op.drop_constraint('contacts_account_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'accounts', ['account_id'], ['id'])
    op.alter_column('deal_items', 'override_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('deal_items_deal_id_fkey', 'deal_items', type_='foreignkey')
    op.create_foreign_key(None, 'deal_items', 'deals', ['deal_id'], ['id'])
    op.alter_column('deals', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('deals', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('deals_created_by_fkey', 'deals', type_='foreignkey')
    op.drop_constraint('deals_source_campaign_id_fkey', 'deals', type_='foreignkey')
    op.drop_constraint('deals_account_id_fkey', 'deals', type_='foreignkey')
    op.drop_constraint('deals_stage_id_fkey', 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'deals', 'campaigns', ['source_campaign_id'], ['id'])
    op.drop_column('deals', 'created_at')
    op.drop_column('deals', 'created_by')
    op.drop_column('deals', 'stage_id')
    op.drop_column('deals', 'notes')
    op.alter_column('invoice_delivery_logs', 'sent_to',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('invoice_delivery_logs', 'sent_cc',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('invoice_delivery_logs_invoice_id_fkey', 'invoice_delivery_logs', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_delivery_logs', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('invoice_items_ticket_id_fkey', 'invoice_items', type_='foreignkey')
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.create_foreign_key(None, 'invoice_items', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('invoices', 'subtotal_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoices', 'gst_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('milestones', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('milestones', 'billable_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint('milestones_project_id_fkey', 'milestones', type_='foreignkey')
    op.create_foreign_key(None, 'milestones', 'projects', ['project_id'], ['id'])
    op.drop_column('milestones', 'is_deleted')
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('projects', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'budget',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint('ticket_contacts_contact_id_fkey', 'ticket_contacts', type_='foreignkey')
    op.drop_constraint('ticket_contacts_ticket_id_fkey', 'ticket_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_contacts', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'ticket_contacts', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint('ticket_materials_ticket_id_fkey', 'ticket_materials', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_materials', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('ticket_time_entries', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ticket_time_entries', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('ticket_time_entries_ticket_id_fkey', 'ticket_time_entries', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_time_entries', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('tickets', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('tickets_account_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_milestone_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'milestones', ['milestone_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'accounts', ['account_id'], ['id'])
    op.drop_column('tickets', 'scheduled_at')
    op.drop_column('tickets', 'service_type')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'created_at')
    op.drop_table('stages')
    op.drop_table('pipelines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('tickets', sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_milestone_id_fkey', 'tickets', 'milestones', ['milestone_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('tickets_account_id_fkey', 'tickets', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('tickets', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'ticket_time_entries', type_='foreignkey')
    op.create_foreign_key('ticket_time_entries_ticket_id_fkey', 'ticket_time_entries', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ticket_time_entries', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ticket_time_entries', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'ticket_materials', type_='foreignkey')
    op.create_foreign_key('ticket_materials_ticket_id_fkey', 'ticket_materials', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ticket_contacts', type_='foreignkey')
    op.drop_constraint(None, 'ticket_contacts', type_='foreignkey')
    op.create_foreign_key('ticket_contacts_ticket_id_fkey', 'ticket_contacts', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ticket_contacts_contact_id_fkey', 'ticket_contacts', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ticket_contacts', 'contact_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ticket_contacts', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'budget',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('products', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('milestones', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.create_foreign_key('milestones_project_id_fkey', 'milestones', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('milestones', 'billable_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('milestones', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoices', 'gst_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('invoices', 'subtotal_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invoice_items_ticket_id_fkey', 'invoice_items', 'tickets', ['ticket_id'], ['id'], ondelete='SET NULL')
    op.alter_column('invoice_items', 'total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'invoice_delivery_logs', type_='foreignkey')
    op.create_foreign_key('invoice_delivery_logs_invoice_id_fkey', 'invoice_delivery_logs', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoice_delivery_logs', 'sent_cc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('invoice_delivery_logs', 'sent_to',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('deals', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('stage_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key('deals_stage_id_fkey', 'deals', 'stages', ['stage_id'], ['id'])
    op.create_foreign_key('deals_account_id_fkey', 'deals', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('deals_source_campaign_id_fkey', 'deals', 'campaigns', ['source_campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('deals_created_by_fkey', 'deals', 'users', ['created_by'], ['id'])
    op.alter_column('deals', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('deals', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'deal_items', type_='foreignkey')
    op.create_foreign_key('deal_items_deal_id_fkey', 'deal_items', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    op.alter_column('deal_items', 'override_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_account_id_fkey', 'contacts', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_audit_id_fkey', 'comments', 'audit_reports', ['audit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comments_deal_id_fkey', 'comments', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comments_ticket_id_fkey', 'comments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comments', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('campaigns', 'budget_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('campaigns', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'campaign_targets', type_='foreignkey')
    op.drop_constraint(None, 'campaign_targets', type_='foreignkey')
    op.create_foreign_key('campaign_targets_contact_id_fkey', 'campaign_targets', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('campaign_targets_campaign_id_fkey', 'campaign_targets', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('campaign_targets_unique', 'campaign_targets', ['campaign_id', 'contact_id'], postgresql_nulls_not_distinct=False)
    op.add_column('audit_reports', sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('assigned_manager_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key('accounts_assigned_manager_id_fkey', 'accounts', 'users', ['assigned_manager_id'], ['id'])
    op.alter_column('accounts', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pipelines_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('stages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('pipeline_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('probability', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name='stages_pipeline_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stages_pkey')
    )
    # ### end Alembic commands ###
