"""add_milestone_description

Revision ID: ce2b5f16d5ca
Revises: e1261c106919
Create Date: 2026-03-02 17:10:02.117192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2b5f16d5ca'
down_revision: Union[str, None] = 'e1261c106919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'description')
    # ### end Alembic commands ###
