"""sync_association_pks

Revision ID: d5626a9d3e1f
Revises: 662138ee3415
Create Date: 2026-01-22 18:08:09.458490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5626a9d3e1f'
down_revision: Union[str, None] = '662138ee3415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_articles', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket_articles', 'article_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ticket_assets', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket_assets', 'asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_assets', 'asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ticket_assets', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ticket_articles', 'article_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ticket_articles', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
