"""add_pending_renewal_invoice_id_to_assets

Revision ID: e1261c106919
Revises: ebecc463a0c2
Create Date: 2026-02-26 00:33:23.937208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1261c106919'
down_revision: Union[str, None] = 'ebecc463a0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('pending_renewal_invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assets', 'invoices', ['pending_renewal_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'pending_renewal_invoice_id')
    # ### end Alembic commands ###
