"""add_sentinel_tracking_to_audits

Revision ID: e3206fe8b3f8
Revises: e76fb1a00ef0
Create Date: 2026-02-06 01:27:56.000949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3206fe8b3f8'
down_revision: Union[str, None] = 'e76fb1a00ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_reports', sa.Column('target_url', sa.String(), nullable=True))
    op.add_column('audit_reports', sa.Column('scan_status', sa.String(), nullable=True))
    op.add_column('audit_reports', sa.Column('last_scan_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_reports', 'last_scan_at')
    op.drop_column('audit_reports', 'scan_status')
    op.drop_column('audit_reports', 'target_url')
    # ### end Alembic commands ###
