"""grand_unification_schema

Revision ID: e76fb1a00ef0
Revises: 05a702abdbd0
Create Date: 2026-02-04 19:02:11.306969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76fb1a00ef0'
down_revision: Union[str, None] = '05a702abdbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('recipient_email', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('event_payload', sa.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('delivery_channel', sa.String(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_notifications_recipient_email'), 'notifications', ['recipient_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_recipient_email'), table_name='notifications')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'delivery_channel')
    op.drop_column('notifications', 'event_payload')
    op.drop_column('notifications', 'recipient_email')
    op.drop_column('contacts', 'notification_preferences')
    # ### end Alembic commands ###
