"""add_article_history_diff_columns

Revision ID: f034e386f7ad
Revises: 32bf70f79f6c
Create Date: 2026-03-07 00:20:42.827945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f034e386f7ad'
down_revision: Union[str, None] = '32bf70f79f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('section_heading', sa.String(), nullable=True))
    op.add_column('article_history', sa.Column('diff_before', sa.Text(), nullable=True))
    op.add_column('article_history', sa.Column('diff_after', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_history', 'diff_after')
    op.drop_column('article_history', 'diff_before')
    op.drop_column('article_history', 'section_heading')
    # ### end Alembic commands ###
