"""add_article_relations

Revision ID: fc78ff647823
Revises: ce2b5f16d5ca
Create Date: 2026-03-03 21:18:09.879925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc78ff647823'
down_revision: Union[str, None] = 'ce2b5f16d5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_relations',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('related_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['related_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'related_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_relations')
    # ### end Alembic commands ###
